# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

required = [
  "github.com/golang/lint/golint",
  "github.com/fzipp/gocyclo",
  "github.com/goadesign/goa/cors",
  "github.com/goadesign/goa/design/apidsl",
  "github.com/goadesign/goa/encoding/form",
  "github.com/goadesign/goa/goagen",
  "github.com/goadesign/goa/goagen/codegen",
  "github.com/goadesign/goa/goagen/gen_app",
  "github.com/goadesign/goa/goagen/gen_controller",
  "github.com/goadesign/goa/goagen/gen_swagger",
  "github.com/goadesign/goa/goagen/utils",
  "github.com/goadesign/goa/goatest",
  "github.com/wadey/gocovmerge",
  "github.com/pilu/fresh",
  "github.com/davecgh/go-spew/spew",
  "github.com/gojuno/minimock/cmd/minimock",
]

[prune]
  go-tests = true
  unused-packages = true

# [[constraint]]
#   name = "github.com/asaskevich/govalidator"
#   version = "5.0.0"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.0.0"

[[constraint]]
  name = "github.com/goadesign/goa"
  version = "=1.3.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "=1.2.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

# [[constraint]]
#   name = "github.com/robfig/cron"
#   version = "1.0.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "0.11.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

# [[constraint]]
#   name = "gopkg.in/asaskevich/govalidator.v4"
#   version = "4.0.0"

[[constraint]]
  name = "github.com/golang/lint"
  revision = "06c8688daad7faa9da5a0c2f163a3d14aac986ca"
  
[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.1"
  
[[constraint]]
  name = "github.com/fzipp/gocyclo"
  revision = "6acd4345c835499920e8426c7e4e8d7a34f1bb83"

[[constraint]]
  name = "github.com/wadey/gocovmerge"
  revision = "b5bfa59ec0adc420475f97f89b58045c721d761c"

[[constraint]]
  name = "github.com/getsentry/raven-go"
  revision = "084a9de9eb0361fbd5ded14b55c84e5493a5d7f6"

[[constraint]]
  name = "github.com/dnaeon/go-vcr"
  revision= "9d71b8a6df86e00127f96bc8dabc09856ab8afdb"

[[constraint]]
  name = "github.com/gojuno/minimock"
  branch = "master"
