= Fabric8 Common

A repository containing all common packages used by the fabric8 services. This repository addresses issue https://github.com/openshiftio/openshift.io/issues/3553[#3553]

Go code shared between fabric8 services can be added here, and then imported by the services.
This will add consistency, reliability, clarity, and (hopefully) reduce bugs and circular repo-to-repo dependencies.

Any code added to this repository should also have test code added, that passes "go test .".

Contents of this repository are anticipated to include:

* Configuration
* Event bus
* Logging
** Common logging format
** Single initialization
** Error handling
** Common HTTP error response format
** Metrics
* Utility
* Validation routines (application name, etc)
* HTTP/REST (closing result body, URL utils)
* Auth
** Loading/parsing public key
** Service Account token management
** JWT token parsing (jwt_token to token_string and token_string to jwt_token)

For Contributing to this project, please refer [CONTRIBUTING.md](CONTRIBUTING.md)
